[package]
name = "evaluation"
version = "0.1.0"
edition = "2021"

[dependencies]
process_mining = {path = "/home/aarkue/doc/projects/rust4pm/process_mining" }
shared = {path = "../shared"}
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"