[package]
name = "evaluation"
version = "0.1.0"
edition = "2021"

[dependencies]
process_mining = {git = "https://github.com/aarkue/rust4pm" }
shared = {path = "../shared"}
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"