[package]
name = "oc_declare"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "oc_declare"
crate-type = ["cdylib"]

[dependencies]
pyo3 = {version = "0.27.1", features = ["macros", "experimental-inspect"]}
shared = {path = "../crates/shared"}
