[build-system]
requires = ["maturin>=1.9,<2.0"]
build-backend = "maturin"

[project]
name = "oc_declare"
readme = "README.md"
description = "Python Bindings for OC-DECLARE: Discovering Object-Centric Declarative Patterns with Synchronization"
authors = [
  {name = "Aaron Küsters", email = "kuesters@pads.rwth-aachen.de"},
]
keywords = ["process-mining", "process", "mining", "OC-DECLARE", "object-centric", "DECLARE"]

requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]


[tool.maturin]
features = ["pyo3/extension-module"]
